import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";

let rows = [];

let config = {
    "type": "service_account",
    "project_id": "quang-anh-crawl",
    "private_key_id": "fba53981b4a0742e364e94bbc6664ba8450ec960",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC2SJaHNQ0qhLHE\nlzpjY08aCAil/fwUs0d2GXMPB9SIg5XvVXHkmiU1cswVrFqLDSq+ynsDtAPNmnD5\nlMaey2eHQjgRH1NJf6VTJIPNccBVZrtnJCCTsIxa2zeMD+/pAK24OwoKrKchFV+1\nkxAWZWGZyEUMVYx/wxm6asdNrw7Hmx1sWXwlC3nsTx3mCYxaZMsWkXb6NmTqefUI\nGxyuM0F8fpUL4S97NI3rkEAvLEnG1WADv6zKiKs2Idnm+K9yvc2i/o59X6macXQe\n1PTLXuoS66GTfVuTx/MvBTVOE/bVbXV6fzUAgY5PrucVDtqoD5oZL5Bd/9YrLeGi\nJpeBCw7RAgMBAAECggEAASRZcb2SwyBY3G5bHV90UdQuOQYAk+D0qBLW6PJHsgGV\ns/hmfIQSYBruQuN/yg0Pe78D1XKFrz58tIo//U4xFu9Cr9QbqY33wJqDCzY0z4Qo\n1T0BdD4VVFtju3L9HIoBIfKYE0Lg0CuqBsFGBvHkfOS85AEkM8e1NqOvyHbkjOUT\nQMRxivTUXjlAHogZYPvMMw98VHpnx4Sv/g1f1hWf796Up/iBenXlYEHvAjOSFfS4\nMMFniI0NrLOSWHX/PK4A7NQfndCnQewXVGN4edgdGDvJnxh+c7o7aXu6jJKEoyqP\n2C9xmvSsSjSu3MtB5hWQFSs0P8CrJkJLSK6fmOdHzQKBgQDp0zHYnrHzrmYGiKk7\n+qY30saeYJSUj+bb5V5SJzyVCwcQDi6AoLftmH4B/Qy/dksbOGS38YTptPwXFU+I\nDD8DjGvhzeaDNvqc+QEBmw7ilk2j5Sb1gf9TNGnK8Ky+DLXOv5yY2GoQrn4lsQ01\nDtL53jh5LIN4zl/oy7R9CV7Z/QKBgQDHkhHh8AJX6d8b+BOgfpoJxFOQw5Jgo3D0\naEoIOkwHN/AMJ7xGcAzPMwcP0QPgB5uVZdItWsDL5KaJfQOyvz8TJIT94hGNHZID\neyohPE+m1cywLfrRYbyw/bBVp0xiZFAkoJ9MW+B4JUk8wTKGDfWzxzr/8V5KLts/\nJwoQXummZQKBgQDflOyS35v1EIvKL57zFUcfFdKJ2nv4Wmk7VuWL1KzfLz4/oe/h\nWszEyg2jRR6NbUV/77qPEMgw2Lg8MkpsIpmWgQ0fS0zhpw6YTpkhuezPyTzQPOu1\n0eoc239VaDElQO4PlbTdigJRlShWTif81gHynwSNCX1lZKDc7vvUm8Mw2QKBgQC1\nFiLp28mUkh8jlt/gUuBdGmslQYCx9bxJ2dPLUXKpXiWQMgIR/Bxzan7u6B7XCrAv\nSNwE0YN9v3Up7mkLqaOHMC0I3jhEzt8uD3U0ATDZVsjL2HztvvzjsN5vakXSRem+\nwoypUfkFq/efjELXBxW60n4DvbVsJMZGsJreLfFfTQKBgDvTcHsr7gJXcxac78cF\ngg/gY/Jpw6QUBxpuE5N0KnTJA1nEK+9oB9A6rCh2rY4fxiv23aKc418XnV7JZhgY\nHYfXGEBbr34x40ggYcFYTxSRDAueZAup7Q4N6Zia7vDqR+21FpTn3f36oMMZlRxJ\nnop+NUY/zpyDTuwmyYOu4ayg\n-----END PRIVATE KEY-----\n",
    "client_email": "quang-anh-crawl-block-chain@quang-anh-crawl.iam.gserviceaccount.com",
    "client_id": "111522593104372647900",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/quang-anh-crawl-block-chain%40quang-anh-crawl.iam.gserviceaccount.com",
    "universe_domain": "googleapis.com"
  };
  
async function getAddressUrls_() {
  // Get the Google Sheet ID
  const sheetId = "1AtWZsGxTiu6MR8tYpypulqxiFs5tLn0qeHrGB0FTcjI";

  // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: config['client_email'],
    key: config['private_key'],
    scopes: ["https://www.googleapis.com/auth/spreadsheets"],
  });

  // Create a service object
  const doc = new GoogleSpreadsheet(sheetId, serviceAccountAuth);
  await doc.loadInfo();

  // sửa dòng này
  const sheet = doc.sheetsByIndex[3];

  // Get the data from the sheet
  return sheet;
};

export const getAddressUrls = getAddressUrls_;
